/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Customers;

/**
 *
 * @author DELL
 */
public class UserOptionPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserOptionPanel
     */
    private int hoveredIndex = -1;

    public UserOptionPanel() {
        initComponents();
        
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        ListOptionUser.setBorder(javax.swing.BorderFactory.createEmptyBorder());

        // Track hover index
        ListOptionUser.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            @Override
            public void mouseMoved(java.awt.event.MouseEvent e) {
                int index = ListOptionUser.locationToIndex(e.getPoint());
                if (index != hoveredIndex) {
                    hoveredIndex = index;
                    ListOptionUser.repaint();
                }
            }
        });
        ListOptionUser.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseExited(java.awt.event.MouseEvent e) {
                hoveredIndex = -1;
                ListOptionUser.repaint();
            }
        });

        // Custom Cell Renderer for hover colors
        ListOptionUser.setCellRenderer(new javax.swing.DefaultListCellRenderer() {
            @Override
            public java.awt.Component getListCellRendererComponent(javax.swing.JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                java.awt.Component c = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                
                setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 10, 8, 10));
                
                if (index == hoveredIndex) {
                    if ("Đăng xuất".equals(value)) {
                        setBackground(new java.awt.Color(220, 53, 69)); // Red
                        setForeground(java.awt.Color.WHITE);
                    } else if (value != null && !value.toString().trim().isEmpty()) {
                        setBackground(new java.awt.Color(0, 120, 215)); // Blue
                        setForeground(java.awt.Color.WHITE);
                    } else {
                        setBackground(java.awt.Color.WHITE);
                        setForeground(java.awt.Color.BLACK);
                    }
                } else {
                    setBackground(java.awt.Color.WHITE);
                    setForeground(java.awt.Color.BLACK);
                }
                
                return c;
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ListOptionUser = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        ListOptionUser.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Hồ sơ", "Tùy chọn", "Cài đặt", "Báo cáo", "Hỗ trợ", "Đăng xuất", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ListOptionUser);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel1))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListOptionUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JList<String> getListOptionUser() {
        return ListOptionUser;
    }

    public javax.swing.JLabel getLogoutLabel() {
        return jLabel1;
    }
}
