/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.CreateAccount;

import java.awt.event.ActionEvent;
import javax.swing.JComboBox;

/**
 *
 * @author DELL
 */
public class CreateUserView extends javax.swing.JFrame {

        /**
         * Creates new form SignInView
         */
        public CreateUserView() {
                initComponents();
                setLocationRelativeTo(null);
                setupUI();
        }

        private void setupUI() {
                nextButton.putClientProperty("JButton.buttonType", "roundRect");
                fullnameField.putClientProperty("JTextField.placeholderText", "Họ và tên");
                gmailField.putClientProperty("JTextField.placeholderText", "Địa chỉ Gmail");
                numberField.putClientProperty("JTextField.placeholderText", "Số điện thoại");
                fullnameField.putClientProperty("JTextField.showClearButton", true);
                gmailField.putClientProperty("JTextField.showClearButton", true);
                numberField.putClientProperty("JTextField.showClearButton", true);

                signInLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                signInLink.addMouseListener(new java.awt.event.MouseAdapter() {
                        @Override
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                signInLinkMouseClicked(evt);
                        }
                });
        }

        private void signInLinkMouseClicked(java.awt.event.MouseEvent evt) {
                this.dispose();
                new View.SignIn.SignInView().setVisible(true);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        fullnameField = new javax.swing.JTextField();
        gmailField = new javax.swing.JTextField();
        numberField = new javax.swing.JTextField();
        addressComboBox = new javax.swing.JComboBox<>();
        nextButton = new javax.swing.JButton();
        signInLink = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 153, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(204, 153, 255));

        jPanel2.setRequestFocusEnabled(false);
        jPanel2.setVerifyInputWhenFocusTarget(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(307, 500));

        jLabel3.setText("Bạn đã có tài khoản?");

        fullnameField.addActionListener(this::fullnameFieldActionPerformed);

        gmailField.addActionListener(this::gmailFieldActionPerformed);

        numberField.addActionListener(this::numberFieldActionPerformed);

        addressComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Chọn Tỉnh/Thành Phố --", "An Giang", "Bắc Ninh", "Cà Mau", "Cao Bằng", "Đắk Lắk", "Điện Biên", "Đồng Nai", "Đồng Tháp", "Gia Lai", "Hà Tĩnh", "Hưng Yên", "Khánh Hòa", "Lai Châu", "Lạng Sơn", "Lào Cai", "Lâm Đồng", "Nghệ An", "Ninh Bình", "Phú Thọ", "Quảng Ngãi", "Quảng Ninh", "Quảng Trị", "Sơn La", "Tây Ninh", "Thanh Hóa", "Thái Nguyên", "TP Cần Thơ", "TP Đà Nẵng", "TP Hà Nội", "TP Hải Phòng", "TP Hồ Chí Minh", "TP Huế", "Tuyên Quang", "Vĩnh Long" }));
        addressComboBox.setToolTipText("-- Chọn Tỉnh Thành Phố --");
        addressComboBox.addActionListener(this::addressComboBoxActionPerformed);

        nextButton.setText("Tiếp Theo");
        nextButton.addActionListener(this::nextButtonActionPerformed);

        signInLink.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        signInLink.setForeground(new java.awt.Color(204, 51, 255));
        signInLink.setText("Đăng nhập");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Khởi tạo thông tin");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(signInLink))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addressComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numberField, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(nextButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fullnameField, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(gmailField, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))))
                .addGap(26, 26, 26))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(fullnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(numberField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(addressComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(signInLink))
                .addGap(73, 73, 73))
        );

        jLabel1.setText("ảnh");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fullnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameFieldActionPerformed

    private void gmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gmailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gmailFieldActionPerformed

        private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {
                String fullname = fullnameField.getText();
                String gmail = gmailField.getText();
                String number = numberField.getText();
                String address = addressComboBox.getSelectedItem() != null ? addressComboBox.getSelectedItem().toString() : "";

                if (fullname.isEmpty() || gmail.isEmpty() || number.isEmpty()) {
                        javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!", "Lỗi",
                                        javax.swing.JOptionPane.ERROR_MESSAGE);
                        return;
                }

                // Validate Email
                String emailRegex = "^[A-Za-z0-9+_.-]+@(.+)$";
                if (!gmail.matches(emailRegex)) {
                        javax.swing.JOptionPane.showMessageDialog(this,
                                        "Email không hợp lệ! Vui lòng nhập đúng định dạng.", "Lỗi",
                                        javax.swing.JOptionPane.ERROR_MESSAGE);
                        return;
                }

                // Validate Phone Number
                String phoneRegex = "^[0-9]{10,10}$";
                if (!number.matches(phoneRegex)) {
                        javax.swing.JOptionPane.showMessageDialog(this,
                                        "Số điện thoại không hợp lệ! Vui lòng nhập lại  .", "Lỗi",
                                        javax.swing.JOptionPane.ERROR_MESSAGE);
                        return;
                }

                Controller.CreateAccount.CreateUserProcess userProcess = new Controller.CreateAccount.CreateUserProcess();
                if (userProcess.isCreated(fullname, gmail, number, address)) {
                        javax.swing.JOptionPane.showMessageDialog(this, "Số điện thoại hoặc Email đã tồn tại!", "Lỗi",
                                        javax.swing.JOptionPane.ERROR_MESSAGE);
                        return;
                }

                // Vô hiệu hóa nút bấm trong lúc xử lý
                nextButton.setEnabled(false);
                nextButton.setText("Đang gửi OTP...");

                new Thread(() -> {
                        String otp = Common.EmailService.generateOTP();
                        boolean sent = Common.EmailService.sendOTP(gmail, otp);

                        javax.swing.SwingUtilities.invokeLater(() -> {
                                nextButton.setEnabled(true);
                                nextButton.setText("Tiếp Theo");

                                if (!sent) {
                                        javax.swing.JOptionPane.showMessageDialog(CreateUserView.this,
                                                        "Không thể gửi email OTP. Vui lòng kiểm tra lại email hoặc kết nối mạng!",
                                                        "Lỗi",
                                                        javax.swing.JOptionPane.ERROR_MESSAGE);
                                        return;
                                }

                                // Chuyển sang màn hình GetRequestAccount
                                GetRequestAccount requestView = new GetRequestAccount(fullname, gmail, number, address,
                                                otp);
                                requestView.setVisible(true);
                                CreateUserView.this.dispose();
                        });
                }).start();
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                // 1. Kích hoạt FlatLaf TẠI ĐÂY (Trước khi tạo Form)
                try {
                        com.formdev.flatlaf.FlatLightLaf.setup();
                } catch (Exception ex) {
                        System.err.println("Không thể khởi tạo FlatLaf");
                }

                java.awt.EventQueue.invokeLater(() -> new CreateUserView().setVisible(true));
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fullnameField;
    private javax.swing.JTextField gmailField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton nextButton;
    private javax.swing.JTextField numberField;
    private javax.swing.JLabel signInLink;
    private javax.swing.JComboBox<String> addressComboBox;
    // End of variables declaration//GEN-END:variables

    private void numberFieldActionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void addressComboBoxActionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
